openapi: 3.1.0
paths:
  /v3/test:
    get:
      summary: test
      operationId: test
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/TestAccountV3"