openapi: 3.1.0
info:
  title: Train Travel API
  version: 1.2.0
paths:
  /bookings:
    get:
      operationId: get-bookings
      summary: List existing bookings
      tags:
        - Bookings
      responses:
        '200':
          description: A list of bookings
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Wrapper-Collection'
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Booking'
                  - properties:
                      links:
                        allOf:
                          - $ref: '#/components/schemas/Links-Self'
                          - $ref: '#/components/schemas/Links-Pagination'
    post:
      operationId: create-booking
      summary: Create a booking
      tags:
        - Bookings
      responses:
        '201':
          description: Booking successful
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Booking'
                  - properties:
                      links:
                        $ref: '#/components/schemas/Links-Self'
  /bookings/{bookingId}/payment:
    post:
      operationId: create-booking-payment
      summary: Pay for a booking
      tags:
        - Payments
      responses:
        '200':
          description: Payment response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/PaymentSucceeded'
                  - $ref: '#/components/schemas/PaymentPending'
components:
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: string
          format: uuid
        trip_id:
          type: string
          format: uuid
        passenger_name:
          type: string
        has_bicycle:
          type: boolean
        has_dog:
          type: boolean
    Wrapper-Collection:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
        links:
          type: object
          readOnly: true
    Links-Self:
      type: object
      properties:
        self:
          type: string
          format: uri
    Links-Pagination:
      type: object
      properties:
        next:
          type: string
          format: uri
        prev:
          type: string
          format: uri
    BookingPayment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        amount:
          type: number
        currency:
          type: string
        source:
          oneOf:
            - $ref: '#/components/schemas/Card'
            - $ref: '#/components/schemas/BankAccount'
        status:
          type: string
          enum:
            - pending
            - succeeded
            - failed
    Card:
      type: object
      properties:
        object:
          type: string
          const: card
        name:
          type: string
        number:
          type: string
        cvc:
          type: string
    BankAccount:
      type: object
      properties:
        object:
          type: string
          const: bank_account
        name:
          type: string
        account_number:
          type: string
    PaymentSucceeded:
      type: object
      properties:
        status:
          type: string
          const: succeeded
        transaction_id:
          type: string
    PaymentPending:
      type: object
      properties:
        status:
          type: string
          const: pending
        estimated_completion:
          type: string
          format: date-time
